---
title: "Set up experiment"
output: html_notebook
params:
  knit_output_format: github_document
  results_root_dir: "."
  experiment:
    value:
      data_path: "https://github.com/broadinstitute/grit-benchmark/raw/main/1.calculate-metrics/cell-health/data/"
      input_structure: "{data_path}/cell_health_merged_feature_select.{extension}"
      extension: csv.gz
      external_metadata: NULL
      add_dummy_metadata_column: FALSE
      split_rows_on_column: NULL
      compact_splits: FALSE
      significance_threshold: 0.05
      parallel_workers: 8
      aggregate_by:
        - Metadata_cell_line
        - Metadata_gene_name
        - Metadata_pert_name
      filter_by: NULL
      reference_set:
        Metadata_gene_name:
          - Chr2
          - Luc
          - LacZ
      random_seed: 42
      background_type: ref
      shuffle: FALSE
      shuffle_bad_groups_threshold: 0.001
      shuffle_group: Metadata_gene_name
      shuffle_strata: NULL
      shuffle_exclude:
        value:
          Metadata_gene_name:
            - Chr2
            - Luc
            - LacZ
            - EMPTY
      subsample_fraction: 1
      subsample_pert_strata:
        - Metadata_gene_name
      subsample_reference_strata:
        - Metadata_Well
      similarity_method: pearson
      sim_params:
        drop_group:
          Metadata_gene_name:
            - EMPTY
        reference:
            Metadata_reference_or_other:
              reference
        all_same_cols_ref:
          - Metadata_cell_line
        all_same_cols_rep:
          - Metadata_cell_line
          - Metadata_gene_name
          - Metadata_reference_or_other
        all_same_cols_rep_ref: NULL
        any_different_cols_non_rep: NULL
        all_same_cols_non_rep: NULL
        all_different_cols_non_rep: NULL
        all_same_cols_group: NULL
        any_different_cols_group: NULL
        annotation_cols:
          - Metadata_cell_line
          - Metadata_gene_name
          - Metadata_reference_or_other
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(logger)
source("utils.R")
```


```{r}
hash <- function(x) stringr::str_sub(digest::digest(x), 1, 8)
```


```{r}
params_x <- params

params_x$results_root_dir <- NULL

results_dir <- file.path(results_root_dir, "results", hash(params_x))

dir.create(results_dir, showWarnings = TRUE, recursive = TRUE)

params %>%
  yaml::write_yaml(file.path(results_dir, "params.yaml"))
```


```{r}
cat(yaml::as.yaml(params))
# print_git_hash(params$experiment$data_path)
```

## Logging

```{r}
log_filename <- file.path(results_dir, "run.log")

if (file.exists(log_filename)) {
  file.remove(log_filename)
}

log_appender(appender_tee(log_filename))

log_info("Logging to {log_filename}...")
```


# Run notebooks

## 1.prepare_data and 2.calculate_index

```{r}
# ----------------------
# Configure input
# ----------------------

input_prefix <- with(params$experiment, glue(input_structure))

if (is.null(params$experiment$plates)) {
  input_profile_files <- list(list(tag = "", filename = input_prefix))
} else {
  input_profile_files <-
    map(params$experiment$plates, function(plate) {
      profile_file <-
        with(params$experiment, glue(input_prefix))
      list(tag = plate, filename = profile_file)
    })
}

# ----------------------
# Configure output
# ----------------------

output_profile_file <- glue("{results_dir}/profiles.parquet")

output_index_file <- glue("{results_dir}/index.parquet")

output_collatedindex_file <-
  glue("{results_dir}/collatedindex.parquet")

# ----------------------
# Check output
# ----------------------

if (file.exists(output_profile_file) &
  file.exists(output_index_file) &
  file.exists(output_collatedindex_file)) {
  log_info(
    "1.prepare_data and 2.calculate_index: skipping for because output files already exist."
  )
} else {
  # ----------------------
  # Create output
  # ----------------------

  parameters <-
    with(
      params$experiment,
      list(
        input_profile_files = input_profile_files,
        output_profile_file = output_profile_file,
        data_path = data_path,
        reference_set = reference_set,
        random_seed = random_seed,
        external_metadata = external_metadata,
        subsample_fraction = subsample_fraction,
        subsample_pert_strata = subsample_pert_strata,
        subsample_reference_strata = subsample_reference_strata,
        shuffle = shuffle,
        shuffle_bad_groups_threshold = shuffle_bad_groups_threshold,
        shuffle_group = shuffle_group,
        shuffle_strata = shuffle_strata,
        shuffle_exclude = shuffle_exclude,
        aggregate_by = aggregate_by,
        filter_by = filter_by,
        add_dummy_metadata_column = add_dummy_metadata_column,
        split_rows_on_column = split_rows_on_column,
        compact_splits = compact_splits
      )
    )

  render_notebook(
    input = "1.prepare_data.Rmd",
    output_dir = results_dir,
    params = parameters
  )

  input_profile_file <- output_profile_file

  parameters <-
    with(
      params$experiment,
      list(
        input_profile_file = input_profile_file,
        output_index_file = output_index_file,
        output_collatedindex_file = output_collatedindex_file,
        sim_params = sim_params
      )
    )

  render_notebook(
    input = "2.calculate_index.Rmd",
    output_dir = results_dir,
    params = parameters
  )
}
```

## 3.calculate_metrics

```{r}

# ----------------------
# Configure input
# ----------------------

input_profile_file <- glue("{results_dir}/profiles.parquet")

input_index_file <- glue("{results_dir}/index.parquet")

input_collatedindex_file <- glue("{results_dir}/collatedindex.parquet")

# ----------------------
# Configure output
# ----------------------

output_collatedsim_file <- glue("{results_dir}/collatedsim.parquet")

output_metrics_file_prefix <- glue("{results_dir}/metrics")

output_metrics_file_status <- glue("{results_dir}/metrics.done")

# ----------------------
# Check output
# ----------------------

if (file.exists(output_collatedsim_file) &
  file.exists(output_metrics_file_status)) {
  log_info("3.calculate_metrics: skipping because output files already exist.")
} else {

  # ----------------------
  # Create output
  # ----------------------

  parameters <-
    with(
      params$experiment,
      list(
        input_profile_file = input_profile_file,
        input_collatedindex_file = input_collatedindex_file,
        output_collatedsim_file = output_collatedsim_file,
        output_metrics_file_prefix = output_metrics_file_prefix,
        similarity_method = similarity_method,
        parallel_workers = parallel_workers
      )
    )

  render_notebook(
    input = "3.calculate_metrics.Rmd",
    output_dir = results_dir,
    params = parameters
  )
}
```

## 4.correct_metrics

```{r}
# ----------------------
# Configure input
# ----------------------

input_collatedsim_file <- glue("{results_dir}/collatedsim.parquet")

input_metrics_file_prefix <- glue("{results_dir}/metrics")

# ----------------------
# Configure output
# ----------------------

type <- params$experiment$background_type

metric_set <- glue("level_1_{type}_null_adjusted")

output_metrics_file_level_1 <- glue("{input_metrics_file_prefix}_{metric_set}.parquet")

metric_set <- glue("level_1_0_{type}_null_adjusted")

output_metrics_file_level_1_0 <- glue("{input_metrics_file_prefix}_{metric_set}.parquet")


# ----------------------
# Create output
# ----------------------


if (file.exists(output_metrics_file_level_1) &
    file.exists(output_metrics_file_level_1_0)) {
  log_info("4.correct_metrics: skipping because output files already exist.")
} else {
  parameters <-
    with(
      params$experiment,
      list(
        input_metrics_file_prefix = input_metrics_file_prefix,
        background_type = background_type,
        random_seed = random_seed,
        significance_threshold = significance_threshold
      )
    )
  
  render_notebook(input = "4.correct_metrics.Rmd",
                  output_dir = results_dir,
                  params = parameters)
}
```

## 5.inspect_metrics

```{r}
# ----------------------
# Configure input
# ----------------------

input_metrics_file_prefix <- glue("{results_dir}/metrics")

# ----------------------
# Create output
# ----------------------

parameters <-
  with(
    params$experiment,
    list(
      input_metrics_file_prefix = input_metrics_file_prefix,
      background_type = background_type
    )
  )

render_notebook(
  input = "5.inspect_metrics.Rmd",
  output_dir = results_dir,
  params = parameters
)
```