---
title: "Prepare data"
output: html_notebook
params:
  data_path: "https://github.com/broadinstitute/grit-benchmark/raw/main/1.calculate-metrics/cell-health/data/"
  input_profile_files:
    value:
      a:
        tag: cellhealth
        filename: "https://github.com/broadinstitute/grit-benchmark/raw/main/1.calculate-metrics/cell-health/data/cell_health_merged_feature_select.csv.gz"
  output_profile_file:
    - "results/test/profiles.parquet"
  aggregate_by:
    - Metadata_cell_line
    - Metadata_gene_name
    - Metadata_pert_name
  filter_by: NULL
  reference_set:
    value:
      Metadata_gene_name:
        - Chr2
        - Luc
        - LacZ
  random_seed: 42
  shuffle: TRUE
  shuffle_bad_groups_threshold: 0.1
  shuffle_group: Metadata_gene_name
  shuffle_strata: NULL
  shuffle_exclude:
    value:
      Metadata_gene_name:
        - Chr2
        - Luc
        - LacZ
        - EMPTY
  subsample_fraction: 1
  subsample_pert_strata:
    - Metadata_gene_name
  subsample_reference_strata:
    - Metadata_Well
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
library(matric)
library(logger)
source("utils.R")
```


```{r}
cat(yaml::as.yaml(params))
```


```{r}
#print_git_hash(params$data_path)
```

# Load profiles

```{r}
(input_profile_files <- map_df(params$input_profile_files, list2DF))
```


```{r}
profiles <-
  pmap_dfr(input_profile_files, function(tag, filename) {
    log_info(glue("Loading {filename} ..."))

    read_file <-
      if(tools::file_ext(basename(filename)) == "parquet") {
        read_parquet
      } else {
        read_csv
      }

    profile <- read_file(filename)

    if (tag != "" | (tag == "" & !("Metadata_Plate" %in% names(profile)))) {
      log_info("Adding a column Metadata_Plate = {tag} to {filename}...")
      profile <- profile %>% mutate(Metadata_Plate = tag)
    }

    profile <- profile %>% select(matches("Metadata_"), everything())

    profile
  })
```

# Aggregate profiles

```{r}
if(!is.null(params$aggregate_by)) {
  variables <-
    names(profiles) %>%
    str_subset("Metadata_", negate = TRUE)

  profiles <-
    profiles %>%
    cytominer::aggregate(variables = variables,
                         strata = params$aggregate_by)
}
```


# Process metadata

## Annotate reference set

```{r}
reference_set <-
  as.data.frame(params$reference_set)
```

```{r}
if(all(names(reference_set) == "path")) {
  reference_set_file <- reference_set$path

  stopifnot(file.exists(reference_set_file))

  log_info("Reading reference set from {reference_set_file} ...")

  reference_set <- read_csv(reference_set_file)

  log_info("Reference set has {n} rows.", n = nrow(reference_set))

}
```


```{r}
reference_col_names <- colnames(reference_set)

profiles <-
  profiles %>%
  select(any_of(reference_col_names)) %>%
  distinct() %>%
  inner_join(reference_set, by = colnames(reference_set)) %>%
  mutate(Metadata_reference_or_other = "reference") %>%
  right_join(profiles) %>%
  mutate(Metadata_reference_or_other = replace_na(Metadata_reference_or_other, "pert")) %>%
  select(matches("^Metadata_"), everything())
```

## Shuffle

```{r}
if (params$shuffle) {
  set.seed(params$random_seed)

  group_col <- params$shuffle_group
  group_col_sym <- sym(group_col)
  
  strata_col <- params$shuffle_strata
  
  if(!is.null(strata_col)) {
    strata_col_sym <- sym(strata_col)
  }

  shuffle_exclude <- as.data.frame(params$shuffle_exclude)

  metadata <- get_annotation(profiles)

  # HACK: these columns are used in the code
  stopifnot(!any(c("g_old", "g_new", "idx") %in% names(metadata)))

  features <- bind_cols(metadata %>% select(id), drop_annotation(profiles))

  metadata_shuffle <-
    metadata %>%
    anti_join(shuffle_exclude, by = names(shuffle_exclude))

  n_groups <- metadata_shuffle %>% distinct(!!group_col_sym) %>% nrow()

  n_bad_shuffle_groups <- Inf

  shuffle_bad_groups_threshold_n <- ceiling(params$shuffle_bad_groups_threshold * n_groups)
  
  while (n_bad_shuffle_groups > shuffle_bad_groups_threshold_n) {

    if (!is.null(strata_col)) {
      metadata_shuffle <-
        metadata_shuffle %>%
        group_by(!!strata_col_sym)
    }
    
    metadata_shuffle <-
      metadata_shuffle %>%
      mutate(idx = sample(id), .before = everything()) %>%
      ungroup()

    map_old <-
      metadata_shuffle %>%
      select(id, g_old = !!group_col_sym)

    map_new <-
      metadata_shuffle %>%
      select(id = idx, g_new = !!group_col_sym)

    df <- inner_join(map_old, map_new, by = "id")

    bad_shuffle_groups <-
      df %>%
      group_by(g_new) %>%
      summarise(n_duplicated = sum(duplicated(g_old))) %>%
      filter(n_duplicated > 0)

    n_bad_shuffle_groups <- nrow(bad_shuffle_groups)

    log_info("n_bad_shuffle_groups = {n_bad_shuffle_groups} (threshold = {shuffle_bad_groups_threshold_n}) ... ")
  }

  log_info("n_bad_shuffle_groups = {n_bad_shuffle_groups}")

  metadata_shuffle <- metadata_shuffle %>% select(-id) %>% rename(id = idx)

  profiles_shuffle <-
    inner_join(metadata_shuffle, features, by = c("id")) %>%
    select(-id)

  profiles <-
    bind_rows(profiles_shuffle,
              profiles %>% inner_join(shuffle_exclude, by = names(shuffle_exclude)))

  profiles <-
    profiles %>%
    select(matches("Metadata_"), everything())

  metadata_shuffle <- get_annotation(profiles)

  stopifnot(all.equal(metadata_shuffle %>% select(-id) %>% arrange(across(everything())),
                      metadata %>% select(-id) %>% arrange(across(everything()))))

  print(bad_shuffle_groups)

}
```

## Downsample

```{r}
if (params$subsample_fraction < 1) {
  set.seed(params$random_seed)

  pert_sample <-
    profiles %>%
    filter(Metadata_reference_or_other != "reference") %>%
    distinct(across(all_of(params$subsample_pert_strata))) %>%
    sample_frac(params$subsample_fraction)

  reference_sample <-
    profiles %>%
    filter(Metadata_reference_or_other == "reference") %>%
    distinct(across(all_of(params$subsample_reference_strata))) %>%
    sample_frac(params$subsample_fraction)

  profiles_experiment <-
    bind_rows(
      profiles %>%
        inner_join(pert_sample, by = params$subsample_pert_strata),
      profiles %>%
        inner_join(reference_sample, by = params$subsample_reference_strata)
    )

  profiles_experiment <-
    profiles_experiment %>%
    select(matches("^Metadata_"), everything())

} else {
  profiles_experiment <- profiles
}
```


```{r}
profiles_experiment %>% count(Metadata_reference_or_other)
```


```{r}
stopifnot(
  profiles_experiment %>%
    count(Metadata_reference_or_other) %>%
    filter(Metadata_reference_or_other == "reference") %>%
    nrow() > 0
)
```

# Filter profiles

```{r}
if(!is.null(params$filter_by)) {
  parquet_file <-
    with(params,
         glue("{input_metrics_file_prefix}_{metric_set}.parquet"))
  
  log_info("Reading {parquet_file} ...")
  
  metrics <- arrow::read_parquet(glue(parquet_file))
  
  profiles_experiment_reference <-
    profiles_experiment %>% 
    filter(Metadata_reference_or_other == "reference")
  
  profiles_experiment_other <-
    profiles_experiment %>% 
    filter(Metadata_reference_or_other != "reference")
  
  profiles_experiment_other_filtered <-
    profiles_experiment_other %>%
    inner_join(metrics %>%
                 filter(.data[[params$filter_by$metric]] > params$filter_by$threshold) %>%
                 select(matches("Metadata_")))
  
  profiles_experiment_filtered <-
    bind_rows(
      profiles_experiment_reference,
      profiles_experiment_other_filtered
    )
  
  log_info("Number of rows in metrics = {nrow(metrics)}")
  
  log_info("Number of rows in profiles_experiment_other = {nrow(profiles_experiment_other)}")
  
  log_info("Number of rows in profiles_experiment_other_filtered = {nrow(profiles_experiment_other_filtered)}")
  
  log_info("Number of rows in profiles_experiment = {nrow(profiles_experiment)}")
  
  log_info("Number of rows in profiles_experiment_filtered = {nrow(profiles_experiment_filtered)}")
  
  profiles_experiment <- profiles_experiment_filtered
}
```

# Save processes profiles

```{r}
attr(profiles_experiment, "params") <- list(prepare_data = params)
```

```{r}
with(params, log_info(glue("Writing {output_profile_file} ...")))

profiles_experiment %>%
  write_parquet(params$output_profile_file)
```
