---
title: "Calculate index"
output: html_notebook
params:
  input_profile_file: "results/test/profiles.parquet"
  output_index_file: "results/test/index.parquet"
  output_collatedindex_file: "results/test/collatedindex.parquet"
  sim_params:
    value:
      drop_group:
        Metadata_gene_name:
          - EMPTY
      reference:
          Metadata_reference_or_other:
            reference
      all_same_cols_ref:
        - Metadata_cell_line
      all_same_cols_rep:
        - Metadata_cell_line
        - Metadata_gene_name
        - Metadata_reference_or_other
      all_same_cols_rep_ref: NULL
      any_different_cols_non_rep: NULL
      all_same_cols_non_rep: NULL
      all_different_cols_non_rep: NULL
      all_same_cols_group: NULL
      any_different_cols_group: NULL
      annotation_cols:
        - Metadata_cell_line
        - Metadata_gene_name
        - Metadata_pert_name
        - Metadata_reference_or_other
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
library(matric)
library(logger)
source("utils.R")
# log_layout(layout_no_timestamp)
```


```{r}
cat(yaml::as.yaml(params))
```


```{r}
list_to_df <-
  function(item) {
    if (!is.null(params$sim_params[[item]])) {
      list2DF(params$sim_params[[item]])
    } else {
      NULL
    }
  }

reference_df <- list_to_df("reference")

drop_group_df <- list_to_df("drop_group")
```

# Load profiles

```{r}
profiles <-
  read_parquet(params$input_profile_file)
```

# Calculate index

```{r}
log_info("Calculating index ...")

sim_df <-
  with(
    params$sim_params,
    matric::sim_calculate(
      population = profiles,
      method = NULL,
      lazy = TRUE,
      all_same_cols_rep_or_group = all_same_cols_rep,
      all_same_cols_ref = all_same_cols_ref,
      reference = reference_df
    )
  )
```


```{r}
attr(sim_df, "params") <-
  c(attr(profiles, "params"),
    list(calculate_index = params))
```


```{r}
with(params, log_info(glue("Writing {output_index_file} ...")))

sim_df %>%
  sim_write(params$output_index_file)
```

# Collate and annotate the index

See https://shntnu.github.io/matric/reference/sim_collate.html#details

```{r}
log_info("Collate and annotate index ...")

collated_sim <-
  with(
    params$sim_params,
    sim_collate(
      sim_df = sim_df,
      reference = reference_df,
      all_same_cols_rep = all_same_cols_rep,
      all_same_cols_rep_ref = all_same_cols_rep_ref,
      all_same_cols_ref = all_same_cols_ref,
      any_different_cols_non_rep = any_different_cols_non_rep,
      all_same_cols_non_rep = all_same_cols_non_rep,
      all_different_cols_non_rep = all_different_cols_non_rep,
      any_different_cols_group = any_different_cols_group,
      all_same_cols_group = all_same_cols_group,
      annotation_cols = annotation_cols,
      drop_group = drop_group_df,
      drop_reference = FALSE
    )
  )
```


```{r}
attr(collated_sim, "params") <-
  c(attr(profiles, "params"),
    list(calculate_index = params))
```


```{r}
with(params, log_info(glue("Writing {output_collatedindex_file} ...")))

collated_sim %>%
  arrow::write_parquet(params$output_collatedindex_file,
    compression = "gzip",
    compression_level = 9
  )
```
