---
title: "Calculate metrics"
output: html_notebook
params:
  input_profile_file: "results/test/profiles.parquet"
  input_collatedindex_file: "results/test/collatedindex.parquet"
  output_collatedsim_file: "results/test/collatedsim.parquet"
  output_metrics_file_prefix: "results/test/metrics"
  similarity_method: pearson
  parallel_workers: 4
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
library(matric)
library(logger)
source("utils.R")
```


```{r}
cat(yaml::as.yaml(params))
```

```{r}
logger::log_threshold(logger::TRACE)
```


```{r}
if (!is.null(params$parallel_workers)) {
  with(params, future::plan(future::multisession, workers = parallel_workers))
}
```

# Load profiles

```{r}
profiles <-
  read_parquet(params$input_profile_file)
```

# Load collated and annotated index

See https://shntnu.github.io/matric/reference/sim_collate.html#details

```{r}
```

# Populate index with similarities

```{r}
if(file.exists(params$output_collatedsim_file)) {
  with(params, log_info("Loading existing collated similarity file {output_collatedsim_file} ... "))

  collated_sim <-
    arrow::read_parquet(params$output_collatedsim_file)

} else {
  log_info("Loading index file ...")

  collated_index <-
    arrow::read_parquet(params$input_collatedindex_file)

  log_info("Populating index with similarities ...")

  collated_sim <-
    sim_calculate_ij(
      population = profiles,
      index = collated_index,
      method = params$similarity_method,
      use_furrr = FALSE
    )

  attr(collated_sim, "params") <-
    c(attr(collated_index, "params"),
      list(calculate_metrics = params))

  with(params, log_info("Writing {output_collatedsim_file} ..."))

  collated_sim %>%
    arrow::write_parquet(
      params$output_collatedsim_file,
      compression = "gzip",
      compression_level = 9
    )
}
```

# Compute metrics

```{r}
log_info("Computing metrics ...")

log_info("Calculating metrics using sim_type_background = 'ref' ...")

metrics_ref <-
  sim_metrics(
    collated_sim,
    sim_type_background = "ref",
    calculate_grouped = FALSE,
    use_furrr = TRUE
  )

names(metrics_ref) <- str_c(names(metrics_ref), "_ref")

metrics <- metrics_ref

if (!is.null(attr(collated_sim, "params")$calculate_index$sim_params$all_same_cols_non_rep)) {
  log_info(
    "Calculating metrics using sim_type_background = 'non_rep' because `all_same_cols_non_rep` is not NULL ..."
  )
  
  metrics_non_rep <-
    sim_metrics(
      collated_sim,
      sim_type_background = "non_rep",
      calculate_grouped = FALSE,
      use_furrr = TRUE
    )
  
  names(metrics_non_rep) <-
    str_c(names(metrics_non_rep), "_non_rep")
  
  metrics <- c(metrics, metrics_non_rep)
}

rm(list = c("metrics_non_rep", "metrics_ref"))

```


```{r}
purrr::walk(names(metrics), function(metric_name) {
  metrics_i <- metrics[[metric_name]]

  attr(metrics_i, "all_same_cols_rep") <- attr(collated_sim, "all_same_cols_rep")

  attr(metrics_i, "metric_metadata") <- attr(collated_sim, "metric_metadata")

  attr(metrics_i, "params") <- attr(collated_sim, "params")

  output_metrics_file_i <- with(params, glue("{output_metrics_file_prefix}_{metric_name}.parquet"))

  log_info("Writing {output_metrics_file_i}...")

  metrics_i %>%
    arrow::write_parquet(
      output_metrics_file_i,
      compression = "gzip",
      compression_level = 9
    )

})

metric_sets_file <- with(params, glue("{output_metrics_file_prefix}_sets.txt"))

names(metrics) %>%
  write_lines(metric_sets_file)

status_file <- with(params, glue("{output_metrics_file_prefix}.done"))

log_info("Writing indicator file {status_file} ...")

file.create(status_file)
```
